### ISSUE TITLE
First focusable item within a group is not reliably found when MenuBar is present

### ISSUE THREAD

**Issue by juuso-vaadin** [vaadin-component-factory/keyboard-shortcut-manager#8]
Sometimes the first element is focused as expected, but after page reload different element may receive focus.

The demo uses _focusNextElement_ action. Each row is defined to be a separate focusable section.
https://user-images.githubusercontent.com/19607782/225577433-0b23c9cd-8a72-4f81-8ed7-b92ea9f09610.mov

The issue seems to appear even with simplified UI when MenuBar is present in view.
![image](https://user-images.githubusercontent.com/19607782/225579900-a1a21b9f-617d-41b1-9dd0-6cec78062f6f.png)

**Comment by OlliTietavainenVaadin** [comment]
Seems to be weirdly component-specific. In a single test UI, I managed to get this consistently happen also with RichTextEditor and MessageInput, but not with ComboBox, DateTimePicker, etc..

**Comment by OlliTietavainenVaadin** [comment]
The behavior is due to MenuBar's overflow implementation, which means a MenuBar's position can't be consistently compared to other elements. This breaks the functionality that finds the first focusable element in a section. 

Version 23.3.9 of VCF Keyboard Shortcut Manager Flow fixes this to a degree by ignoring elements that report `DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC` when compared with `compareDocumentPosition`, which works unless such a component is the first one that should be focused in the section.
